if(OI_DEPENDENCY)
    foreach(DEPENDENCY ${OI_DEPENDENCY})
        set(CMAKE_PREFIX_PATH "OI")
        string(TOUPPER ${DEPENDENCY} PACKAGE_NAME)
        find_package(OI_${PACKAGE_NAME})
        if(OI_${PACKAGE_NAME}_FOUND)
            message("add dependency \"${DEPENDENCY}\" for ${PROJECT_NAME}")
        else()
            message("\"${DEPENDENCY}\" not found for ${PROJECT_NAME}")
            set(EXTERNAL_DEPENDENCY ${DEPENDENCY})
            include(${OI_CMAKE_PATH}/cmake/ExternalComponent.cmake)
        endif()
    endforeach(DEPENDENCY)
else()
    message("No dependency for ${PROJECT_NAME}")
endif()
